import "./globals.css";
import Header from "@/components/Header";

export const metadata = {
  title: "Shahzaib Noor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <header>
          <Header />
        </header> */}
        {/* <main> */}
        {children}
        {/* </main> */}
        {/* <footer>
          <h1>Footer</h1>
        </footer> */}
      </body>
    </html>
  );
}
